/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'text' : string,
  'author' : UserId,
  'timestamp' : Time,
}
export interface Question {
  'id' : QuestionId,
  'text' : string,
  'isAnonymous' : boolean,
  'answer' : [] | [Answer],
  'author' : [] | [UserId],
  'timestamp' : Time,
  'isAnswered' : boolean,
}
export type QuestionId = bigint;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'displayName' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'answerQuestion' : ActorMethod<[QuestionId, string], Answer>,
  'askQuestion' : ActorMethod<[string, boolean], Question>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteQuestion' : ActorMethod<[QuestionId], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuidanceText' : ActorMethod<[], string>,
  'getQuestion' : ActorMethod<[QuestionId], [] | [Question]>,
  'getQuestionsByUser' : ActorMethod<[UserId], Array<Question>>,
  'getUnansweredQuestions' : ActorMethod<[], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportContent' : ActorMethod<[QuestionId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];