/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionId = IDL.Nat;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Answer = IDL.Record({
  'text' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'answer' : IDL.Opt(Answer),
  'author' : IDL.Opt(UserId),
  'timestamp' : Time,
  'isAnswered' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'answerQuestion' : IDL.Func([QuestionId, IDL.Text], [Answer], []),
  'askQuestion' : IDL.Func([IDL.Text, IDL.Bool], [Question], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteQuestion' : IDL.Func([QuestionId], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuidanceText' : IDL.Func([], [IDL.Text], ['query']),
  'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(Question)], ['query']),
  'getQuestionsByUser' : IDL.Func([UserId], [IDL.Vec(Question)], ['query']),
  'getUnansweredQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportContent' : IDL.Func([QuestionId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionId = IDL.Nat;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Answer = IDL.Record({
    'text' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'answer' : IDL.Opt(Answer),
    'author' : IDL.Opt(UserId),
    'timestamp' : Time,
    'isAnswered' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'answerQuestion' : IDL.Func([QuestionId, IDL.Text], [Answer], []),
    'askQuestion' : IDL.Func([IDL.Text, IDL.Bool], [Question], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteQuestion' : IDL.Func([QuestionId], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuidanceText' : IDL.Func([], [IDL.Text], ['query']),
    'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(Question)], ['query']),
    'getQuestionsByUser' : IDL.Func([UserId], [IDL.Vec(Question)], ['query']),
    'getUnansweredQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportContent' : IDL.Func([QuestionId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };